jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16.13.1', '17.1.0' ]
    name: Test on Node.js ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - name: Setup modules
        run: npm i
      - name: Run example
        run: npm run example
name: test
on:
  push:
    branches: [ main ]
